# Generated by Django 4.2 on 2023-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_agenda_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
