# Generated by Django 4.2 on 2023-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_socio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
